name: Submission Evaluation

on:
  pull_request:
    paths:
      - 'submissions/**'

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        pip install torch torchvision torchaudio torch-geometric scikit-learn pandas
    - name: Evaluate submission
      run: |
        python evaluate.py
